
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.95
decorations = "none"

[font]
normal.family = "Fira Code"

#regular
size = 14

[general]
import = ["~/.config/alacritty/themes/themes/aura.toml"]

#for video
# size = 35.0
