
[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.98
decorations = "none"

[font]

#regular
size = 14
normal = { family = "FiraCode Nerd Font", style = "Regular" }

[general]
import = ["~/.config/alacritty/themes/themes/aura.toml"]

#for video
# size = 35.0
